/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-05-31 16:36:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import models.BeanUser;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("models.BeanUser");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("   \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Exemple Formulari </title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/form.css\" />\n");
      out.write("<script type=\"text/javascript\" src=\"jquery/jquery-1.7.1.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"jquery/jquery.validate.js\"></script>\n");
      out.write("<script>\n");
      out.write("$(document).ready(function(){\n");
      out.write("    $(\"#registerForm\").validate({\n");
      out.write("    \tsubmitHandler: function(form) {\n");
      out.write("    \t\t$('#content').load('formcontroller',$(\"#registerForm\").serialize());\n");
      out.write("    },\n");
      out.write("    rules: {\n");
      out.write("    \tnickname: \"required\",\n");
      out.write("\t    mail: \"required\",\n");
      out.write("\t    gender: \"required\",\n");
      out.write("\t    contraseña: \"required\",\n");
      out.write("    \tnombre: \"required\",\n");
      out.write("\t    mail_again: {\n");
      out.write("\t    \tequalTo: \"#mail\"\n");
      out.write("\t    },\n");
      out.write("\t    contraseña_again:{\n");
      out.write("\t  \t\tequalTo: \"#contraseña\"\n");
      out.write("\t    }\n");
      out.write("\t  }\n");
      out.write("    });\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
 
BeanUser user = null;
if (request.getAttribute("user")!=null) {
	user = (BeanUser)request.getAttribute("user");
}
else {
	user = new BeanUser();
}

      out.write("\n");
      out.write("\n");
      out.write("<form id=registerForm action=\"\" method=\"POST\">\n");
      out.write("<table>\n");
      out.write("<tr> \n");
      out.write("<td> Nickname </td> \n");
      out.write("<td> <input type=\"text\" name=\"nickname\" value=\"");
      out.print(user.getNickname() );
      out.write("\" id=\"nickname\" class=\"required\" minlength=\"3\" maxlength=\"16\"/> </td> \n");
 	
	if ( user.getError()[0] == 1) {
		
      out.write(" \n");
      out.write("\t\t<td class=\"error\"> The username already exists in our DB! </td>  \n");
      out.write("\t\t");
 
	}

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</tr>\n");
      out.write("<tr> \n");
      out.write("<td> Correo Electrónico </td> <td> <input type=\"text\" name=\"mail\"  value = \"");
      out.print(user.getMail() );
      out.write("\" id=\"mail\" class=\"required email\"/> </td>\n");
      out.write(" </tr>\n");
      out.write(" \n");
      out.write(" <tr> \n");
      out.write("<td> Repita Correo Electrónico </td> <td> <input type=\"text\" name=\"mail_again\"  value = \"");
      out.print(user.getMail_again() );
      out.write("\" id=\"mail_again\" /> </td>\n");
      out.write(" </tr>\n");
      out.write(" \n");
      out.write("  <tr> \n");
      out.write("<td> Nombre </td> <td> <input type=\"text\" name=\"nombre\"  value = \"");
      out.print(user.getNombre() );
      out.write("\" id=\"nombre\" /> </td>\n");
      out.write(" </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" <tr>\n");
      out.write(" <td> Fecha de Nacimiento</td><td>\n");
      out.write("\n");
      out.write("<select name=\"day\" title=\"Día\" id=\"day\" >\n");
      out.write("<option selected=\"1\" value=\"0\">Día</option>\n");
      out.write("<option value=\"1\">1</option>\n");
      out.write("<option value=\"2\">2</option>\n");
      out.write("<option value=\"3\">3</option>\n");
      out.write("<option value=\"4\">4</option>\n");
      out.write("<option value=\"5\">5</option>\n");
      out.write("<option value=\"6\">6</option>\n");
      out.write("<option value=\"7\">7</option>\n");
      out.write("<option value=\"8\">8</option>\n");
      out.write("<option value=\"9\">9</option>\n");
      out.write("<option value=\"10\">10</option>\n");
      out.write("<option value=\"11\">11</option>\n");
      out.write("<option value=\"12\">12</option>\n");
      out.write("<option value=\"13\">13</option>\n");
      out.write("<option value=\"14\">14</option>\n");
      out.write("<option value=\"15\">15</option>\n");
      out.write("<option value=\"16\">16</option>\n");
      out.write("<option value=\"17\">17</option>\n");
      out.write("<option value=\"18\">18</option>\n");
      out.write("<option value=\"19\">19</option>\n");
      out.write("<option value=\"20\">20</option>\n");
      out.write("<option value=\"21\">21</option>\n");
      out.write("<option value=\"22\">22</option>\n");
      out.write("<option value=\"23\">23</option>\n");
      out.write("<option value=\"24\">24</option>\n");
      out.write("<option value=\"25\">25</option>\n");
      out.write("<option value=\"26\">26</option>\n");
      out.write("<option value=\"27\">27</option>\n");
      out.write("<option value=\"28\">28</option>\n");
      out.write("<option value=\"29\">29</option>\n");
      out.write("<option value=\"30\">30</option>\n");
      out.write("<option value=\"31\">31</option>\n");
      out.write("</select>\n");
      out.write("\n");
      out.write("\n");
      out.write("<select name=\"month\" title=\"Mes\" id=\"month\">\n");
      out.write("<option selected=\"1\" value=\"0\">Mes</option>\n");
      out.write("<option value=\"1\">1</option>\n");
      out.write("<option value=\"2\">2</option>\n");
      out.write("<option value=\"3\">3</option>\n");
      out.write("<option value=\"4\">4</option>\n");
      out.write("<option value=\"5\">5</option>\n");
      out.write("<option value=\"6\">6</option>\n");
      out.write("<option value=\"7\">7</option>\n");
      out.write("<option value=\"8\">8</option>\n");
      out.write("<option value=\"9\">9</option>\n");
      out.write("<option value=\"10\">10</option>\n");
      out.write("<option value=\"11\">11</option>\n");
      out.write("<option value=\"12\">12</option>\n");
      out.write("</select>\n");
      out.write("\n");
      out.write("\n");
      out.write("<select name=\"year\" title=\"year\">\n");
      out.write("<option selected=\"1\" value=\"0\">Año</option>\n");
      out.write("<option value=\"2016\">2016</option>\n");
      out.write("<option value=\"2015\">2015</option>\n");
      out.write("<option value=\"2014\">2014</option>\n");
      out.write("<option value=\"2013\">2013</option>\n");
      out.write("<option value=\"2012\">2012</option>\n");
      out.write("<option value=\"2011\">2011</option>\n");
      out.write("<option value=\"2010\">2010</option>\n");
      out.write("<option value=\"2009\">2009</option>\n");
      out.write("<option value=\"2008\">2008</option>\n");
      out.write("<option value=\"2007\">2007</option>\n");
      out.write("<option value=\"2006\">2006</option>\n");
      out.write("<option value=\"2005\">2005</option>\n");
      out.write("<option value=\"2004\">2004</option>\n");
      out.write("<option value=\"2003\">2003</option>\n");
      out.write("<option value=\"2002\">2002</option>\n");
      out.write("<option value=\"2001\">2001</option>\n");
      out.write("<option value=\"2000\">2000</option>\n");
      out.write("<option value=\"1999\">1999</option>\n");
      out.write("<option value=\"1998\">1998</option>\n");
      out.write("<option value=\"1997\">1997</option>\n");
      out.write("<option value=\"1996\">1996</option>\n");
      out.write("<option value=\"1995\">1995</option>\n");
      out.write("<option value=\"1994\">1994</option>\n");
      out.write("<option value=\"1993\">1993</option>\n");
      out.write("<option value=\"1992\">1992</option>\n");
      out.write("<option value=\"1991\">1991</option>\n");
      out.write("<option value=\"1990\">1990</option>\n");
      out.write("<option value=\"1989\">1989</option>\n");
      out.write("<option value=\"1988\">1988</option>\n");
      out.write("<option value=\"1987\">1987</option>\n");
      out.write("<option value=\"1986\">1986</option>\n");
      out.write("<option value=\"1985\">1985</option>\n");
      out.write("<option value=\"1984\">1984</option>\n");
      out.write("<option value=\"1983\">1983</option>\n");
      out.write("<option value=\"1982\">1982</option>\n");
      out.write("<option value=\"1981\">1981</option>\n");
      out.write("<option value=\"1980\">1980</option>\n");
      out.write("<option value=\"1979\">1979</option>\n");
      out.write("<option value=\"1978\">1978</option>\n");
      out.write("<option value=\"1977\">1977</option>\n");
      out.write("<option value=\"1976\">1976</option>\n");
      out.write("<option value=\"1975\">1975</option>\n");
      out.write("<option value=\"1974\">1974</option>\n");
      out.write("<option value=\"1973\">1973</option>\n");
      out.write("<option value=\"1972\">1972</option>\n");
      out.write("<option value=\"1971\">1971</option>\n");
      out.write("<option value=\"1970\">1970</option>\n");
      out.write("<option value=\"1969\">1969</option>\n");
      out.write("<option value=\"1968\">1968</option>\n");
      out.write("<option value=\"1967\">1967</option>\n");
      out.write("<option value=\"1966\">1966</option>\n");
      out.write("<option value=\"1965\">1965</option>\n");
      out.write("<option value=\"1964\">1964</option>\n");
      out.write("<option value=\"1963\">1963</option>\n");
      out.write("<option value=\"1962\">1962</option>\n");
      out.write("<option value=\"1961\">1961</option>\n");
      out.write("<option value=\"1960\">1960</option>\n");
      out.write("<option value=\"1959\">1959</option>\n");
      out.write("<option value=\"1958\">1958</option>\n");
      out.write("<option value=\"1957\">1957</option>\n");
      out.write("<option value=\"1956\">1956</option>\n");
      out.write("<option value=\"1955\">1955</option>\n");
      out.write("<option value=\"1954\">1954</option>\n");
      out.write("<option value=\"1953\">1953</option>\n");
      out.write("<option value=\"1952\">1952</option>\n");
      out.write("<option value=\"1951\">1951</option>\n");
      out.write("<option value=\"1950\">1950</option>\n");
      out.write("<option value=\"1949\">1949</option>\n");
      out.write("<option value=\"1948\">1948</option>\n");
      out.write("<option value=\"1947\">1947</option>\n");
      out.write("<option value=\"1946\">1946</option>\n");
      out.write("<option value=\"1945\">1945</option>\n");
      out.write("<option value=\"1944\">1944</option>\n");
      out.write("<option value=\"1943\">1943</option>\n");
      out.write("<option value=\"1942\">1942</option>\n");
      out.write("<option value=\"1941\">1941</option>\n");
      out.write("<option value=\"1940\">1940</option>\n");
      out.write("<option value=\"1939\">1939</option>\n");
      out.write("<option value=\"1938\">1938</option>\n");
      out.write("<option value=\"1937\">1937</option>\n");
      out.write("<option value=\"1936\">1936</option>\n");
      out.write("<option value=\"1935\">1935</option>\n");
      out.write("<option value=\"1934\">1934</option>\n");
      out.write("<option value=\"1933\">1933</option>\n");
      out.write("<option value=\"1932\">1932</option>\n");
      out.write("<option value=\"1931\">1931</option>\n");
      out.write("<option value=\"1930\">1930</option>\n");
      out.write("<option value=\"1929\">1929</option>\n");
      out.write("<option value=\"1928\">1928</option>\n");
      out.write("<option value=\"1927\">1927</option>\n");
      out.write("<option value=\"1926\">1926</option>\n");
      out.write("<option value=\"1925\">1925</option>\n");
      out.write("<option value=\"1924\">1924</option>\n");
      out.write("<option value=\"1923\">1923</option>\n");
      out.write("<option value=\"1922\">1922</option>\n");
      out.write("<option value=\"1921\">1921</option>\n");
      out.write("<option value=\"1920\">1920</option>\n");
      out.write("<option value=\"1919\">1919</option>\n");
      out.write("<option value=\"1918\">1918</option>\n");
      out.write("<option value=\"1917\">1917</option>\n");
      out.write("<option value=\"1916\">1916</option>\n");
      out.write("<option value=\"1915\">1915</option>\n");
      out.write("<option value=\"1914\">1914</option>\n");
      out.write("<option value=\"1913\">1913</option>\n");
      out.write("<option value=\"1912\">1912</option>\n");
      out.write("<option value=\"1911\">1911</option>\n");
      out.write("<option value=\"1910\">1910</option>\n");
      out.write("<option value=\"1909\">1909</option>\n");
      out.write("<option value=\"1908\">1908</option>\n");
      out.write("<option value=\"1907\">1907</option>\n");
      out.write("<option value=\"1906\">1906</option>\n");
      out.write("<option value=\"1905\">1905</option>\n");
      out.write("</select>\n");
      out.write("\n");
      out.write("</td>\n");
      out.write("<td>\n");
 	
	if ( user.getError()[1] == 1) {
		
      out.write(" \n");
      out.write("\t\t<td class=\"error\"> Invalid date </td>  \n");
      out.write("\t\t");
 
	}

      out.write("\n");
      out.write("\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write(" \n");
      out.write(" \n");
      out.write(" \n");
      out.write("  <tr> \n");
      out.write("<td>Sexo</td><td> Hombre  <input type=\"radio\" name=\"sexo\"  value = \"0\" id=\"sexo\"/>\t<br>\n");
      out.write(" Mujer  <input type=\"radio\" name=\"sexo\"  value = \"1\" id=\"sexo\" /> </td>\n");
      out.write(" </tr>\n");
      out.write("\n");
      out.write(" \n");
      out.write(" <tr>\n");
      out.write(" <td>Contraseña</td><td><input type=\"password\" name=\"contraseña\" value = \"\" id=\"contraseña\" minlength=\"6\" maxlength=\"16\"/></td>\n");
      out.write(" </tr>\n");
      out.write(" \n");
      out.write(" <tr>\n");
      out.write(" <td>Repita contraseña</td><td><input type=\"password\" name=\"contraseña_again\" value = \"\" id=\"contraseña_again\" /></td>\n");
      out.write(" </tr>\n");
      out.write("<tr>\n");
      out.write("<td> <input name=\"sumbit\" type=\"submit\" value=\"Enviar\"> </td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
