/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-05-31 16:36:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\n");
      out.write("<title> Practica3 </title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/structure.css\" />\n");
      out.write("<script type=\"text/javascript\" src=\"jquery/jquery-1.7.1.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("$(document).ready(function() {\n");
      out.write("    $(\".menu\").click(function(event) {\n");
      out.write("        $('#content').load('Content',{content: $(this).attr('id')});\n");
      out.write("           });\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");

HttpSession session = request.getSession(false);
String link = "login.jsp";
if ((session != null) && (session.getAttribute("nickname")!=null)) {
	link = "loginOk.jsp";
}

      out.write("\n");
      out.write("\n");
      out.write("   <!-- Begin Wrapper -->\n");
      out.write("   <div id=\"wrapper\">\n");
      out.write("   \n");
      out.write("         <!-- Begin Header -->\n");
      out.write("         <div id=\"header\">\n");
      out.write("\t\t \n");
      out.write("\t\t       <h1>Social Engineer</h1>\t\t \n");
      out.write("\t\t\t   \n");
      out.write("\t\t </div>\n");
      out.write("\t\t <!-- End Header -->\n");
      out.write("\t\t \n");
      out.write("\t\t <!-- Begin Navigation -->\n");
      out.write("         <div id=\"navigation\">\n");
      out.write("\t\t \n");
      out.write("\t     ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\n");
      out.write("\t\t\t   \n");
      out.write("\t\t </div>\n");
      out.write("\t\t <!-- End Navigation -->\n");
      out.write("\t\t \n");
      out.write("         <!-- Begin Faux Columns -->\n");
      out.write("\t\t <div id=\"faux\">\n");
      out.write("\t\t \n");
      out.write("\t\t       <!-- Begin Left Column -->\n");
      out.write("\t\t       <div id=\"leftcolumn\">\n");
      out.write("\t\t \n");
      out.write("\t\t             \n");
      out.write("\t\t \n");
      out.write("\t\t       </div>\n");
      out.write("\t\t       <!-- End Left Column -->\n");
      out.write("\t\t \n");
      out.write("\t\t       <!-- Begin Content Column -->\n");
      out.write("\t\t       <div id=\"content\">\n");
      out.write("\t\t       \n");
      out.write("\t\t       ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, link , out, false);
      out.write("\n");
      out.write("\t  \t\t       \t\t\t  \n");
      out.write("\t\t       </div>\n");
      out.write("\t\t       <!-- End Content Column -->\n");
      out.write("\t\t\t   \n");
      out.write("\t\t\t   \n");
      out.write("\t\t\t   \n");
      out.write("\t\t\t   <!-- Begin Right Column -->\n");
      out.write("\t\t       <div id=\"rightcolumn\">\n");
      out.write("\t\t \n");
      out.write("\t\t             \n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t       </div>\n");
      out.write("\t\t       <!-- End Right Column -->\n");
      out.write("\n");
      out.write("         </div>\t   \n");
      out.write("         <!-- End Faux Columns --> \n");
      out.write("\n");
      out.write("         <!-- Begin Footer -->\n");
      out.write("         <div id=\"footer\">\n");
      out.write("\t\t       \n");
      out.write("               This is the Footer\t\t\n");
      out.write("\n");
      out.write("         </div>\n");
      out.write("\t\t <!-- End Footer -->\n");
      out.write("\t\t \n");
      out.write("   </div>\n");
      out.write("   <!-- End Wrapper -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
